#!/usr/bin/env node
// Generate @viliha/vui-core from the one source of truth, packages/ui/src.
//
// The React package already contains framework-free modules: the theming
// engine, the table import/export helpers, and `cn`. Rather than move them out
// (which would make @viliha/vui-ui depend on this package, and every React
// consumer pay for a refactor that buys them nothing), this package compiles
// the same files for everyone else.
//
// Same trick as packages/theme: `src/` and `dist/` here are generated and
// git-ignored, so there is no second copy in the tree to drift.
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const UI_SRC = join(root, "..", "ui", "src");

// Framework-free modules only. A file lands here when it imports no UI
// framework, not because it happens to be useful: the check below enforces it.
const MODULES = ["class-variants", "theme-config", "table-io", "utils"];

const src = join(root, "src");
rmSync(src, { recursive: true, force: true });
mkdirSync(src, { recursive: true });

for (const name of MODULES) {
  const from = join(UI_SRC, `${name}.ts`);
  const code = readFileSync(from, "utf8");
  if (/from\s+["'](react|react-dom|vue|svelte)["']/.test(code) || code.includes('"use client"')) {
    console.error(`core: ${name}.ts is not framework-free any more, so it cannot ship here`);
    process.exit(1);
  }
  copyFileSync(from, join(src, `${name}.ts`));
}

writeFileSync(
  join(src, "index.ts"),
  `// Generated by scripts/build.mjs. Edit the sources in packages/ui/src.\n` +
    MODULES.map((m) => `export * from "./${m}.js";\n`).join(""),
);

rmSync(join(root, "dist"), { recursive: true, force: true });
execFileSync("npx", ["--no-install", "tsc", "-p", join(root, "tsconfig.json")], {
  cwd: root,
  stdio: "inherit",
});

console.log(`vui-core: built ${MODULES.length + 1} modules from packages/ui/src`);
